import os

username = "user" #@param {type:"string"}

password = "root" #@param {type:"string"}

print("Creating User and Setting it up")

os.system(f"useradd -m {username}")

os.system(f"adduser {username} sudo")

os.system(f"echo '{username}:{password}' | sudo chpasswd")

os.system("sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd")

print("User Created and Configured")
